# theme/colors.py

# Base colors
BLACK = "#000000"
WHITE = "#BFBFBF"
BEIGE = "#F6FABD"

# Green palette
GREEN_DARKEST = "#022326"
GREEN_DARK = "#034040"
GREEN = "#035951"
GREEN_LIGHT = "#00A385"

# Semantic names
PRIMARY = GREEN
PRIMARY_DARK = GREEN_DARK
BACKGROUND = GREEN_DARKEST
SURFACE = GREEN_DARK
TEXT = WHITE
ACCENT = BEIGE